#!/usr/bin/env python3
"""
HTML report generation for ppigFinder.

This module is intentionally independent from the GUI. The first version
creates a simple self-contained HTML report. Later it can include genome
maps, AF3 tables, PAE images and downloadable TSV blocks.
"""

from __future__ import annotations

from html import escape
from pathlib import Path
from datetime import datetime


def _table(headers: list[str], rows: list[list[object]]) -> str:
    th = "".join(f"<th>{escape(str(header))}</th>" for header in headers)

    body = []
    for row in rows:
        tds = "".join(f"<td>{escape(str(value))}</td>" for value in row)
        body.append(f"<tr>{tds}</tr>")

    return f"<table><thead><tr>{th}</tr></thead><tbody>{''.join(body)}</tbody></table>"


def render_basic_report(
    title: str,
    genome_name: str | None = None,
    genome_length: int | None = None,
    orfs: list[dict] | None = None,
    interaction_results: list[dict] | None = None,
) -> str:
    """
    Render a basic standalone HTML report.
    """
    orfs = orfs or []
    interaction_results = interaction_results or []

    orf_rows = []
    for i, orf in enumerate(orfs, start=1):
        orf_rows.append([
            f"ORF{i}",
            orf.get("start", ""),
            orf.get("end", ""),
            orf.get("strand", ""),
            orf.get("frame", ""),
            orf.get("length", ""),
            round(float(orf.get("gc", 0.0)), 2) if orf.get("gc") is not None else "",
            orf.get("source", ""),
        ])

    interaction_rows = []
    for item in interaction_results:
        interaction_rows.append([
            item.get("name", ""),
            item.get("iptm", ""),
            item.get("ptm", ""),
            item.get("ranking_score", ""),
            item.get("pae_inter", ""),
            item.get("pae_min", ""),
            item.get("classification", ""),
        ])

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{escape(title)}</title>
<style>
body {{
    font-family: Arial, Helvetica, sans-serif;
    margin: 32px;
    color: #263238;
    background: #fafafa;
}}
h1, h2 {{
    color: #1b3a4b;
}}
.section {{
    background: #ffffff;
    border: 1px solid #dde3e6;
    border-radius: 10px;
    padding: 18px;
    margin-bottom: 20px;
}}
table {{
    border-collapse: collapse;
    width: 100%;
    font-size: 13px;
}}
th {{
    background: #e8f0f4;
    text-align: left;
}}
th, td {{
    border: 1px solid #d7dee2;
    padding: 6px 8px;
}}
.meta {{
    color: #607d8b;
    font-size: 13px;
}}
</style>
</head>
<body>
<h1>{escape(title)}</h1>
<p class="meta">Generated by ppigFinder on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>

<div class="section">
<h2>Genome summary</h2>
<p><strong>Name:</strong> {escape(str(genome_name or ""))}</p>
<p><strong>Length:</strong> {escape(str(genome_length or ""))}</p>
<p><strong>Predicted ORFs:</strong> {len(orfs)}</p>
<p><strong>Interaction results:</strong> {len(interaction_results)}</p>
</div>

<div class="section">
<h2>ORF table</h2>
{_table(["ID", "Start", "End", "Strand", "Frame", "Length", "GC %", "Source"], orf_rows)}
</div>

<div class="section">
<h2>AlphaFold interaction results</h2>
{_table(["Name", "ipTM", "pTM", "Ranking", "PAE inter", "PAE min", "Class"], interaction_rows)}
</div>
</body>
</html>
"""
    return html


def write_basic_report(path: str | Path, **kwargs) -> None:
    """
    Write a basic HTML report.
    """
    path = Path(path)
    html = render_basic_report(**kwargs)

    with path.open("w", encoding="utf-8") as handle:
        handle.write(html)
