#!/usr/bin/env python3
"""
Default ppigFinder scientific workflow.
"""

from __future__ import annotations

from ppigfinder.workflows.models import WorkflowDefinition, WorkflowStage, WorkflowStep


def build_default_workflow() -> WorkflowDefinition:
    """
    Build the default stepwise analysis workflow.
    """
    return WorkflowDefinition(
        id="ppigfinder_default",
        title="ppigFinder analysis workflow",
        description=(
            "Stepwise workflow from genome input to ORF prediction, annotation, "
            "AlphaFold/PPI analysis and final reporting."
        ),
        stages=[
            WorkflowStage(
                id="start",
                title="Start",
                description="Create, open or restore an analysis session.",
                steps=[
                    WorkflowStep(
                        id="open_genome",
                        title="Open genome",
                        stage="start",
                        data_type="genome",
                        description="Load a genome or nucleotide sequence into ppigFinder.",
                        input_data="FASTA, GenBank or SnapGene DNA file",
                        output_data="Genome sequence and metadata",
                        action_name="load_fasta",
                        tab_hint="Genome",
                    ),
                    WorkflowStep(
                        id="open_project",
                        title="Open project",
                        stage="start",
                        data_type="project",
                        description="Open a previously saved ppigFinder project.",
                        input_data="ppigFinder project file",
                        output_data="Restored project state",
                        action_name="load_project",
                    ),
                    WorkflowStep(
                        id="import_snapshot",
                        title="Import project snapshot",
                        stage="start",
                        data_type="project",
                        description="Import a versioned snapshot with genome, ORFs, annotations and AF3 results.",
                        input_data="Project Snapshot v3 JSON",
                        output_data="Restored versioned project state",
                        action_name="import_project_snapshot",
                        optional=True,
                    ),
                ],
            ),
            WorkflowStage(
                id="sequence",
                title="DNA / Genome processing",
                description="Prepare DNA/genome data for downstream protein analyses.",
                steps=[
                    WorkflowStep(
                        id="genome_overview",
                        title="Genome overview",
                        stage="sequence",
                        data_type="genome",
                        description="Inspect genome size, GC content, ORF count and loaded metadata.",
                        input_data="Loaded genome",
                        output_data="Genome summary",
                        tab_hint="Genome",
                        requires=["open_genome"],
                    ),
                    WorkflowStep(
                        id="translate_genome",
                        title="Translate genome",
                        stage="sequence",
                        data_type="dna",
                        description="Translate nucleotide sequence or selected regions into protein sequence.",
                        input_data="DNA sequence",
                        output_data="Protein sequence",
                        action_name="translate_genome",
                        tab_hint="DNA",
                        requires=["open_genome"],
                        optional=True,
                    ),
                    WorkflowStep(
                        id="export_map",
                        title="Export genome map",
                        stage="sequence",
                        data_type="genome",
                        description="Export the current genome/ORF map as a publication or report figure.",
                        input_data="Genome coordinates and ORF annotations",
                        output_data="PDF genome map",
                        action_name="export_map_pdf",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                ],
            ),
            WorkflowStage(
                id="orfs",
                title="Protein / ORF prediction",
                description="Predict and export protein-coding ORFs.",
                steps=[
                    WorkflowStep(
                        id="predict_orfs",
                        title="Predict ORFs",
                        stage="orfs",
                        data_type="orf",
                        description="Predict protein-coding ORFs using Pyrodigal, six-frame scanning or hybrid mode.",
                        input_data="DNA/genome sequence",
                        output_data="ORF table and protein sequences",
                        action_name="analyze_orfs",
                        requires=["open_genome"],
                    ),
                    WorkflowStep(
                        id="review_orfs",
                        title="Review ORF table",
                        stage="orfs",
                        data_type="orf",
                        description="Inspect ORF coordinates, strand, frame, size, GC and annotation columns.",
                        input_data="Predicted ORFs",
                        output_data="Curated ORF selection",
                        tab_hint="Genome",
                        requires=["predict_orfs"],
                    ),
                    WorkflowStep(
                        id="export_orf_fasta",
                        title="Export ORF FASTA",
                        stage="orfs",
                        data_type="protein",
                        description="Export predicted ORF protein sequences in FASTA format.",
                        input_data="Predicted protein sequences",
                        output_data="Protein FASTA",
                        action_name="save_fasta",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                ],
            ),
            WorkflowStage(
                id="annotation",
                title="Annotation",
                description="Annotate protein similarity, conserved domains and genomic context.",
                steps=[
                    WorkflowStep(
                        id="blast_query",
                        title="BLAST search",
                        stage="annotation",
                        data_type="protein",
                        description="Search a protein query against predicted ORFs using BLAST+ or fallback algorithms.",
                        input_data="Protein query and predicted ORFs",
                        output_data="Similarity hits mapped to ORFs",
                        action_name="run_blast",
                        tab_hint="BLAST Query",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                    WorkflowStep(
                        id="hmm_domains",
                        title="HMM domain annotation",
                        stage="annotation",
                        data_type="annotation",
                        description="Annotate conserved domains using HMMER3 or built-in domain scanner fallback.",
                        input_data="Predicted protein sequences",
                        output_data="Domain annotations per ORF",
                        action_name="annotate_hmm",
                        tab_hint="HMM",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                    WorkflowStep(
                        id="neighborhood",
                        title="Neighborhood analysis",
                        stage="annotation",
                        data_type="genome",
                        description="Inspect ORF genomic neighborhoods for operon/context interpretation.",
                        input_data="ORF genomic coordinates",
                        output_data="Neighborhood context",
                        tab_hint="Neighborhood",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                ],
            ),
            WorkflowStage(
                id="alphafold",
                title="AlphaFold / PPI",
                description="Prepare, import and score predicted protein-protein interactions.",
                steps=[
                    WorkflowStep(
                        id="export_af3_server_json",
                        title="Export AF3 Server JSON",
                        stage="alphafold",
                        data_type="alphafold",
                        description="Generate AlphaFold Server/web JSON for selected ORF protein pairs.",
                        input_data="Selected ORF protein pairs",
                        output_data="AlphaFold Server JSON",
                        action_name="export_af3_server_json",
                        tab_hint="AF3 Server",
                        requires=["predict_orfs"],
                        optional=True,
                    ),
                    WorkflowStep(
                        id="import_af3_results",
                        title="Import AF3 results",
                        stage="alphafold",
                        data_type="alphafold",
                        description="Parse AlphaFold 3 result folders and extract ipTM, pTM, PAE and interaction metrics.",
                        input_data="AF3 output folders",
                        output_data="Parsed AF3 result table",
                        action_name="import_af3_results_folder",
                        tab_hint="AlphaFold",
                        optional=True,
                    ),
                    WorkflowStep(
                        id="export_af3_table",
                        title="Export AF3 results table",
                        stage="alphafold",
                        data_type="report",
                        description="Export parsed AlphaFold interaction metrics as TSV/CSV.",
                        input_data="Parsed AF3 results",
                        output_data="AF3 TSV/CSV table",
                        action_name="export_af3_results_table",
                        requires=["import_af3_results"],
                        optional=True,
                    ),
                ],
            ),
            WorkflowStage(
                id="reporting",
                title="Reports / System",
                description="Generate final outputs and inspect runtime environment.",
                steps=[
                    WorkflowStep(
                        id="html_report",
                        title="HTML report",
                        stage="reporting",
                        data_type="report",
                        description="Generate a standalone HTML report from the current project snapshot.",
                        input_data="Genome, ORFs, annotations and AF3 results",
                        output_data="HTML report",
                        action_name="export_html_report",
                        optional=True,
                    ),
                    WorkflowStep(
                        id="backend_status",
                        title="Backend status",
                        stage="reporting",
                        data_type="system",
                        description="Check availability of BLAST+, HMMER3, Pyrodigal and SSH/Paramiko.",
                        input_data="Runtime environment",
                        output_data="Backend availability table",
                        action_name="show_backend_status",
                        optional=True,
                    ),
                    WorkflowStep(
                        id="export_snapshot",
                        title="Export project snapshot",
                        stage="reporting",
                        data_type="project",
                        description="Export a versioned JSON snapshot for reproducible reporting and future reanalysis.",
                        input_data="Current ppigFinder session",
                        output_data="Project Snapshot v3 JSON",
                        action_name="export_project_snapshot",
                        optional=True,
                    ),
                ],
            ),
        ],
    )
